version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - vol_wp:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
  mariadb:
    restart: on-failure
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - vol_mariadb:/var/lib/mysql
  wordpress:
    restart: on-failure
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - vol_wp:/var/www/html
    depends_on:
      - mariadb
  adminer:
    restart: on-failure
    container_name: adminer
    build: ./requirements/bonus/Adminer
    image: adminer
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  ftp:
    restart: on-failure
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "60000-60005:60000-60005"
      - "21:21"
      - "20:20"
    volumes:
      - vol_wp:/home/kid-bouh
    depends_on:
      - wordpress
  redis:
    restart: on-failure
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
  website:
    container_name: website
    build: ./requirements/bonus/website
    image: website
    networks:
      - inception
    ports:
      - "1337:80"
  cadvisor:
    restart: on-failure
    container_name: cadvisor
    build: ./requirements/bonus/cadv
    image: cadvisor
    networks:
      - inception
    ports:
      - "3030:8080"
    volumes:
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/:/rootfs:ro"
      - "/sys:/sys:ro"
      - "/var/run:/var/run:ro"
volumes:
  vol_wp:
    driver_opts:
      type: none
      o: bind
      device: /home/kid-bouh/data/wp
  vol_mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/kid-bouh/data/mariadb
networks:
  inception:
    driver: bridge