version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - vol_wp:/var/www/html
  mariadb:
    restart: on-failure
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - vol_mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - vol_wp:/var/www/html
  adminer:
    container_name: adminer
    build: ./requirements/bonus/Adminer
    image: adminer
    networks:
      - inception
    ports:
      - "8080:8080"
volumes:
  vol_wp:
    driver_opts:
      type: none
      o: bind
      device: /Users/kid-bouh/data/wp
  vol_mariadb:
    driver_opts:
      type: none
      o: bind
      device: /Users/kid-bouh/data/mariadb
networks:
  inception:
    driver: bridge