FROM debian:buster

RUN apt-get update -y; apt-get upgrade -y; apt-get install curl -y; curl -L https://github.com/google/cadvisor/releases/download/v0.37.5/cadvisor -o cadvisor; chmod +x cadvisor;

CMD ./cadvisor -logtostderr